In [1]:
# !git clone https://github.com/beichenzbc/Long-CLIP.git


In [29]:
cd Long-CLIP


[Errno 2] No such file or directory: 'Long-CLIP'
/Users/shaonimukherjee/Code Playground/longclip/Long-CLIP/eval/classification/imagenet


In [4]:
from model import longclip
import torch
from PIL import Image
import numpy as np

In [5]:
device = "cuda" if torch.cuda.is_available() else "cpu"
model, preprocess = longclip.load("./checkpoints/longclip-B.pt", device=device)

In [6]:
text = longclip.tokenize(["A man is crossing the street with a red car parked nearby.", "A man is driving a car in an urban scene."]).to(device)
image = preprocess(Image.open("./img/demo.png")).unsqueeze(0).to(device)

In [7]:
with torch.no_grad():
    image_features = model.encode_image(image)
    text_features = model.encode_text(text)
    
    logits_per_image, logits_per_text = model(image, text)
    probs = logits_per_image.softmax(dim=-1).cpu().numpy()

print("Label probs:", probs) # prints: [[0.982  0.01799]]

Label probs: [[0.98200136 0.01799861]]


In [11]:
ls

__pycache__/    classes.py      imagenet.py
categories.txt  data_loader.py  templates.py


In [12]:
text = longclip.tokenize(["A cat jumping.", "A cat sleeping."]).to(device)
image = preprocess(Image.open("./img/cat.jpg")).unsqueeze(0).to(device)

In [13]:
with torch.no_grad():
    image_features = model.encode_image(image)
    text_features = model.encode_text(text)
    
    logits_per_image, logits_per_text = model(image, text)
    probs = logits_per_image.softmax(dim=-1).cpu().numpy()

print("Label probs:", probs)

Label probs: [[0.00201881 0.99798125]]


In [16]:
text = longclip.tokenize(["A dog walking with a human.", "A dog talking with a human."]).to(device)
image = preprocess(Image.open("./img/dog_Walk.jpg")).unsqueeze(0).to(device)

In [17]:
with torch.no_grad():
    image_features = model.encode_image(image)
    text_features = model.encode_text(text)
    
    logits_per_image, logits_per_text = model(image, text)
    probs = logits_per_image.softmax(dim=-1).cpu().numpy()

print("Label probs:", probs)

Label probs: [[0.9423362  0.05766385]]


In [8]:
# text_features

tensor([[-0.0531,  0.1650, -0.0865,  ...,  0.3076,  0.1851,  0.1972],
        [ 0.0181, -0.0699,  0.2107,  ...,  0.1637, -0.0913,  0.3545]])

In [12]:
image_features[0][:10]

tensor([ 0.1384, -0.1739, -0.0762, -0.0642,  0.3947, -0.6165,  0.3728,  1.0172,
         0.4740, -0.1217])

In [13]:
text_features[0][:10]

tensor([-0.0531,  0.1650, -0.0865,  0.0483,  0.3860,  0.1215,  0.0982,  0.0265,
         0.2142, -0.1879])